dependencies:
- name: consul
  repository: "@stable"
  version: 3.4.x
- name: mongodb
  version: 0.4.18
  repository: "@stable"
- name: nginx-ingress
  version: 0.28.x
  repository: "@stable"
- name: elasticsearch
  version: 1.8.x
  repository: "@incubator"
