dependencies:
- name: consul
  version: 3.4.x
  repository: "@stable"
- name: mongodb
  version: 0.4.18
  repository: "@stable"
- name: traefik
  version: 1.52.x
  repository: "@stable"
- name: elasticsearch
  version: 1.8.x
  repository: "@incubator"
