dependencies:
- name: mongodb
  version: 4.3.x
  repository: "@stable"
- name: nginx-ingress
  version: 0.28.x
  repository: "@stable"
- name: elasticsearch
  version: 1.8.x
  repository: "@incubator"
