dependencies:
- name: consul
  version: 3.x.x
  repository: "@stable"
- name: mongodb
  version: 4.x.x
  repository: "@stable"
- name: elasticsearch
  version: x.x.x
  # version: 6.1.1
  repository: "@incubator"
