apiVersion: v1
kind: Service
metadata:
  name: analyzer
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: headless
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: reportportal-analyzer
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: analyzer
  labels: {{ include "labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: reportportal-analyzer
  serviceName: analyzer
  replicas: 1
  template:
    metadata:
      labels:
        component: reportportal-analyzer
    spec:
      containers:
      - name: analyzer
        image: "reportportal/service-analyzer:{{ .Values.analyzer.version }}"
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: ES_HOSTS
          value: "http://elasticsearch:9200"
{{ include "nodeSelector" . | indent 8 }}
