apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: analyzer
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-analyzer
  serviceName: analyzer-0
  template:
    metadata:
      labels:
        component: reportportal-analyzer
    spec:
      containers:
      -  image: "{{ .Values.registry }}reportportal/service-analyzer:{{ .Values.analyzer.version }}"
        name: analyzer
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: ES_HOSTS
          value: http://elasticsearch:9200
{{ include "nodeSelector" . | indent 8 }}
