apiVersion: v1
kind: Service
metadata:
  name: api
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: headless
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: reportportal-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels: {{ include "labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: reportportal-api
  replicas: 1
  serviceName: api
  template:
    metadata:
      labels:
        component: reportportal-api
    spec:
      containers:
      - name: api
        image: "reportportal/service-api:{{ .Values.api.version }}"
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: JAVA_OPTS
          value: "-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
        - name: RP_PROFILES
          value: "docker"
        # - name: RP_MONGO_URI
        #   value: mongodb://localhost:27017
{{ include "nodeSelector" . | indent 8 }}
