apiVersion: v1
kind: Service
metadata:
  name: api
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: headless
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: reportportal-api
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  labels: {{ include "labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: reportportal-api
  replicas: 1
  serviceName: api
  template:
    metadata:
      labels:
        component: reportportal-api
    spec:
      hostname: api
      containers:
      - name: api
        image: "reportportal/service-api:{{ .Values.api.version }}"
        livenessProbe:
          httpGet:
            path: /api/v1/admin/health
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 15
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: JAVA_OPTS
          value: "-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
        - name: RP_PROFILES
          value: "docker"
        - name: RP_MONGO_URI
          value: "mongodb://{{ .Release.Name }}-mongodb:27017"
{{ include "nodeSelector" . | indent 8 }}
