{{- if .Values.elasticsearch.persistence -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reportportal-elasticsearch
  labels: {{ include "labels" . | indent 4 }}
spec:
  claimRef:
    namespace: default
    name: reportportal-elasticsearch
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.elasticsearch.persistence }}
  hostPath:
    path: /mnt/data/elastic
{{- end -}}
