apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: "9998"
    port: 9998
    protocol: TCP
    targetPort: 9998
  - name: "9999"
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    component: reportportal-gateway
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-gateway
  serviceName: gateway
  template:
    metadata:
      labels:
        component: reportportal-gateway
    spec:
      containers:
      - name: gateway
        image: "fabiolb/fabio:1.5.8-go1.10"
        ports:
        - containerPort: 9998
          protocol: TCP
        - containerPort: 9999
          protocol: TCP
        env:
        - name: FABIO_PROXY_ADDR
          value: :9999;rt=300s;wt=300s
        - name: FABIO_REGISTRY_CONSUL_ADDR
          value: registry:8500
        - name: FABIO_REGISTRY_CONSUL_REGISTER_NAME
          value: gateway
{{ include "nodeSelector" . | indent 8 }}
