apiVersion: v1
kind: Service
metadata:
  name: index
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: headless
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    component: reportportal-index
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: index
  labels: {{ include "labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: reportportal-index
  replicas: 1
  serviceName: index
  template:
    metadata:
      labels:
        component: reportportal-index
    spec:
      containers:
      - name: index
        image: "reportportal/service-index:{{ .Values.index.version }}"
        ports:
        - containerPort: 8090
          protocol: TCP
        env:
        - name: RP_PROXY_CONSUL
          value: "true"
        - name: RP_SERVER_PORT
          value: "8090"
{{ include "nodeSelector" . | indent 8 }}
