apiVersion: v1
kind: Service
metadata:
  name: index
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: headless
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: reportportal-index
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: index
  labels: {{ include "labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: reportportal-index
  replicas: 1
  serviceName: index
  template:
    metadata:
      labels:
        component: reportportal-index
    spec:
      hostname: index
      containers:
      - name: index
        image: "reportportal/service-index:{{ .Values.index.version }}"
        readynessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /info
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        # - name: RP_PROXY_CONSUL
        #   value: "true"
        - name: RP_SERVER_PORT
          value: "8080"
{{ include "nodeSelector" . | indent 8 }}
