{{- if .Values.mongodb.persistence -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reportportal-mongodb
  labels: {{ include "labels" . | indent 4 }}
spec:
  claimRef:
    namespace: default
    name: reportportal-mongodb
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.persistence.mongodb.size }}
  hostPath:
    path: /mnt/data/db
{{- end -}}
