apiVersion: v1
kind: Service
metadata:
  name: uat
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: headless
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: reportportal-uat
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uat
  labels: {{ include "labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: reportportal-uat
  replicas: 1
  serviceName: uat
  template:
    metadata:
      labels:
        component: reportportal-uat
    spec:
      containers:
      - name: uat
        image: "reportportal/service-authorization:{{ .Values.authorization.version }}"
        readinessProbe:
          httpGet:
            path: /info
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: RP_PROFILES
          value: "docker"
        - name: RP_SESSION_LIVE
          value: "86400"
{{ include "nodeSelector" . | indent 8 }}
