apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: ui
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-ui
  serviceName: ui
  template:
    metadata:
      labels:
        component: reportportal-ui
    spec:
      containers:
        - name: ui
          image: "reportportal/service-ui:{{ .Values.ui.version }}"
          ports:
          - containerPort: 8080
            protocol: TCP
          - env:
            - name: RP_CONSUL.ADDRESS
              value: registry:8500
            - name: RP_CONSUL.TAGS
              value: urlprefix-/ui opts strip=/ui
            - name: RP_SERVER.PORT
              value: 8080
{{ include "nodeSelector" . | indent 8 }}
