apiVersion: v1
kind: Service
metadata:
  name: ui
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: headless
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: reportportal-ui
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels: {{ include "labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: reportportal-ui
  replicas: 1
  serviceName: ui
  template:
    metadata:
      labels:
        component: reportportal-ui
    spec:
      containers:
      - name: ui
        image: "reportportal/service-ui:{{ .Values.ui.version }}"
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: RP_CONSUL.ADDRESS
          value: "registry:8500"
        - name: RP_CONSUL.TAGS
          value: "urlprefix-/ui opts strip=/ui"
        - name: RP_SERVER.PORT
          value: "8080"
{{ include "nodeSelector" . | indent 8 }}
