apiVersion: v1
kind: Service
metadata:
  name: ui
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: headless
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: reportportal-ui
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
  labels: {{ include "labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: reportportal-ui
  replicas: 1
  serviceName: ui
  template:
    metadata:
      labels:
        component: reportportal-ui
    spec:
      containers:
      - name: ui
        image: "reportportal/service-ui:{{ .Values.ui.version }}"
        readinessProbe:
          httpGet:
            path: /info
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        # - name: RP_CONSUL_ADDRESS
        #   value: ""
        # - name: RP_CONSUL.TAGS
        #   value: "urlprefix-/ui opts strip=/ui"
        - name: RP_SERVER_PORT
          value: "8080"
{{ include "nodeSelector" . | indent 8 }}
